/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroyRouteImport } from './routes/zeroy'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionsSurfaceIdRouteImport } from './routes/extensions_.$surfaceId'
import { Route as ExtensionAssetsSplatRouteImport } from './routes/extension-assets.$'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ZeroyConnectCallbackRouteImport } from './routes/zeroy.connect.callback'

const ZeroyRoute = ZeroyRouteImport.update({
  id: '/zeroy',
  path: '/zeroy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsSurfaceIdRoute = ExtensionsSurfaceIdRouteImport.update({
  id: '/extensions_/$surfaceId',
  path: '/extensions/$surfaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionAssetsSplatRoute = ExtensionAssetsSplatRouteImport.update({
  id: '/extension-assets/$',
  path: '/extension-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroyConnectCallbackRoute = ZeroyConnectCallbackRouteImport.update({
  id: '/connect/callback',
  path: '/connect/callback',
  getParentRoute: () => ZeroyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/zeroy': typeof ZeroyRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/extension-assets/$': typeof ExtensionAssetsSplatRoute
  '/extensions/$surfaceId': typeof ExtensionsSurfaceIdRoute
  '/zeroy/connect/callback': typeof ZeroyConnectCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/zeroy': typeof ZeroyRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/extension-assets/$': typeof ExtensionAssetsSplatRoute
  '/extensions/$surfaceId': typeof ExtensionsSurfaceIdRoute
  '/zeroy/connect/callback': typeof ZeroyConnectCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/zeroy': typeof ZeroyRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/extension-assets/$': typeof ExtensionAssetsSplatRoute
  '/extensions_/$surfaceId': typeof ExtensionsSurfaceIdRoute
  '/zeroy/connect/callback': typeof ZeroyConnectCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extensions'
    | '/zeroy'
    | '/api/$'
    | '/extension-assets/$'
    | '/extensions/$surfaceId'
    | '/zeroy/connect/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extensions'
    | '/zeroy'
    | '/api/$'
    | '/extension-assets/$'
    | '/extensions/$surfaceId'
    | '/zeroy/connect/callback'
  id:
    | '__root__'
    | '/'
    | '/extensions'
    | '/zeroy'
    | '/api/$'
    | '/extension-assets/$'
    | '/extensions_/$surfaceId'
    | '/zeroy/connect/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionsRoute: typeof ExtensionsRoute
  ZeroyRoute: typeof ZeroyRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ExtensionAssetsSplatRoute: typeof ExtensionAssetsSplatRoute
  ExtensionsSurfaceIdRoute: typeof ExtensionsSurfaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zeroy': {
      id: '/zeroy'
      path: '/zeroy'
      fullPath: '/zeroy'
      preLoaderRoute: typeof ZeroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions_/$surfaceId': {
      id: '/extensions_/$surfaceId'
      path: '/extensions/$surfaceId'
      fullPath: '/extensions/$surfaceId'
      preLoaderRoute: typeof ExtensionsSurfaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension-assets/$': {
      id: '/extension-assets/$'
      path: '/extension-assets/$'
      fullPath: '/extension-assets/$'
      preLoaderRoute: typeof ExtensionAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zeroy/connect/callback': {
      id: '/zeroy/connect/callback'
      path: '/connect/callback'
      fullPath: '/zeroy/connect/callback'
      preLoaderRoute: typeof ZeroyConnectCallbackRouteImport
      parentRoute: typeof ZeroyRoute
    }
  }
}

interface ZeroyRouteChildren {
  ZeroyConnectCallbackRoute: typeof ZeroyConnectCallbackRoute
}

const ZeroyRouteChildren: ZeroyRouteChildren = {
  ZeroyConnectCallbackRoute: ZeroyConnectCallbackRoute,
}

const ZeroyRouteWithChildren = ZeroyRoute._addFileChildren(ZeroyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionsRoute: ExtensionsRoute,
  ZeroyRoute: ZeroyRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ExtensionAssetsSplatRoute: ExtensionAssetsSplatRoute,
  ExtensionsSurfaceIdRoute: ExtensionsSurfaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
