<?php

defined('ABSPATH') || exit;

function zeroy_theme_units_verification_failures(string $theme_directory): array
{
    $source_path = rtrim($theme_directory, '/') . '/' . ZEROY_THEME_PROGRAM_SOURCE_PATH;
    $compiled = zeroy_runtime_theme_units_compiled_manifest($theme_directory);
    if (!is_file($source_path)) {
        return $compiled === null ? [] : [zeroy_runtime_verification_failure('theme_program_orphaned_output', 'A handwritten-only ThemeArtifact cannot retain generated ThemeUnit outputs.', ZEROY_THEME_UNIT_PROGRAM_PATH, 1, 'Compiled output exists without zeroy.units.json.', 'Delete zeroy.units.json through the SiteCheckout; the compiler will remove every generated unit path.')];
    }
    if (is_wp_error($compiled)) return [zeroy_runtime_verification_failure($compiled->get_error_code(), 'Compiled ThemeProgram must bind exact generated bytes.', ZEROY_THEME_UNIT_PROGRAM_PATH, 1, $compiled->get_error_message(), 'Repair zeroy.units.json or unit source in the same SiteCheckout and let the compiler regenerate outputs.')];
    $program_json = zeroy_theme_units_read_json_file($source_path, '/');
    $program = $program_json['ok'] ? zeroy_theme_units_decode_program($program_json['value']) : $program_json;
    $resolved = $program['ok'] ? zeroy_theme_units_resolve_sources($theme_directory, $program['value']) : $program;
    $theme_manifest = zeroy_runtime_theme_runtime_manifest($theme_directory);
    $fresh = $resolved['ok'] && !is_wp_error($theme_manifest) ? zeroy_theme_units_compile_resolved($program['value'], $resolved['value'], $theme_manifest['zcss']['styles']) : $resolved;
    if (($fresh['ok'] ?? false) !== true) return [zeroy_runtime_verification_failure('theme_program_source_invalid', 'ThemeProgram source graph must compile through the pinned resolver and compiler.', ZEROY_THEME_PROGRAM_SOURCE_PATH, 1, zeroy_runtime_json($fresh['diagnostics'] ?? []), 'Inspect themeUnitContract/themeUnitSurface and repair the same SiteCheckout.')];
    foreach ($fresh['value']['outputs'] as $path => $bytes) {
        $actual = file_get_contents(rtrim($theme_directory, '/') . '/' . $path);
        if (!is_string($actual) || $actual !== $bytes) return [zeroy_runtime_verification_failure('theme_program_generated_output_mismatch', 'Generated ThemeUnit bytes must equal a fresh compilation of the closed source graph.', $path, 1, 'Generated output differs from deterministic recompilation.', 'Do not write generated paths; restage source files so the SiteCheckout compiler replaces them.')];
    }
    return [];
}
