export default Object.freeze({
  source: "src/pi/extension.ts",
  hostModules: Object.freeze(["@earendil-works/pi-coding-agent"]),
  profile: Object.freeze({
    kind: "multi-file",
    assets: Object.freeze(["CHANGELOG.md", "CONTRIBUTING.md", "dist/browser-extension", "docs"]),
  }),
  expected: Object.freeze({
    commands: Object.freeze([]),
    tools: Object.freeze([
      "chrome_click",
      "chrome_console",
      "chrome_drag",
      "chrome_enable",
      "chrome_evaluate",
      "chrome_fill",
      "chrome_hover",
      "chrome_inspect",
      "chrome_navigate",
      "chrome_network_get",
      "chrome_network_list",
      "chrome_press",
      "chrome_read",
      "chrome_screenshot",
      "chrome_scroll",
      "chrome_snapshot",
      "chrome_status",
      "chrome_tab_activate",
      "chrome_tab_close",
      "chrome_tab_group",
      "chrome_tab_list",
      "chrome_tab_new",
      "chrome_tab_ungroup",
      "chrome_tap",
      "chrome_type",
      "chrome_upload",
      "chrome_wait",
    ]),
    handlers: Object.freeze([
      "before_agent_start",
      "session_shutdown",
      "session_start",
      "session_tree",
    ]),
  }),
});
