<?php

defined('ABSPATH') || exit;

function zeroy_zcss_compiler_source_hash(): string
{
    return ZEROY_ZCSS_COMPILER_SOURCE_HASH;
}

function zeroy_zcss_tokens_css(array $tokens): string
{
    $declarations = [];
    foreach ($tokens as $name => $value) $declarations[$name] = $value;
    $light = ":root {\n" . zeroy_zcss_declarations($declarations) . "\n}";
    $dark = [
        '--z-color-surface' => '#0f172a',
        '--z-color-on-surface' => '#f8fafc',
        '--z-color-surface-muted' => '#1e293b',
        '--z-color-border' => '#475569',
    ];
    return $light . "\n@media (prefers-color-scheme: dark) {\n  :root {\n" . zeroy_zcss_declarations($dark, '    ') . "\n  }\n}";
}

function zeroy_zcss_compile(mixed $input): array
{
    $decoded = zeroy_zcss_decode_design($input);
    if (!$decoded['ok']) return $decoded;
    $design = $decoded['design'];
    $compiled_tokens = zeroy_zcss_compile_tokens($design);
    if (!$compiled_tokens['ok']) return $compiled_tokens;
    $css = "/* Generated by " . ZEROY_ZCSS_COMPILER_ID . "; do not edit. */\n"
        . zeroy_zcss_tokens_css($compiled_tokens['map']) . "\n"
        . zeroy_zcss_primitives_css() . "\n";
    $design_hash = zeroy_zcss_hash($design);
    $output_hash = hash('sha256', $css);
    $contract = [
        'contract' => ZEROY_ZCSS_COMPILED_CONTRACT,
        'compiler' => ['id' => ZEROY_ZCSS_COMPILER_ID, 'version' => ZEROY_ZCSS_COMPILER_VERSION, 'sourceHash' => zeroy_zcss_compiler_source_hash()],
        'designHash' => $design_hash,
        'outputHash' => $output_hash,
        'tokens' => $compiled_tokens['tokens'],
        'primitives' => zeroy_zcss_public_primitives(),
        'rules' => ['reservedClassPrefix' => 'z-', 'reservedPropertyPrefix' => '--z-'],
        'browserPolicy' => zeroy_zcss_browser_policy(),
        'warnings' => [],
    ];
    return [
        'ok' => true,
        'design' => $design,
        'css' => $css,
        'manifest' => $contract,
        'manifestJson' => zeroy_zcss_canonical_json($contract),
    ];
}

function zeroy_zcss_authoring_contract(): array
{
    $compiled = zeroy_zcss_compile(zeroy_zcss_minimal_design_document());
    $tokens = array_map(
        static fn(array $token): array => array_intersect_key($token, ['name' => true, 'category' => true]),
        $compiled['manifest']['tokens'],
    );
    return [
        'contract' => 'zeroy/zcss-authoring@1',
        'designContract' => ZEROY_ZCSS_DESIGN_CONTRACT,
        'compiledContract' => ZEROY_ZCSS_COMPILED_CONTRACT,
        'compiler' => ['id' => ZEROY_ZCSS_COMPILER_ID, 'version' => ZEROY_ZCSS_COMPILER_VERSION, 'sourceHash' => zeroy_zcss_compiler_source_hash()],
        'schema' => zeroy_zcss_design_json_schema(),
        'minimalDocument' => zeroy_zcss_minimal_design_document(),
        'tokens' => $tokens,
        'primitives' => zeroy_zcss_public_primitives(),
        'browserPolicy' => zeroy_zcss_browser_policy(),
        'contrastPairs' => zeroy_zcss_contrast_pairs(),
        'namespaces' => [
            'compilerClasses' => '.z-*',
            'compilerProperties' => '--z-*',
            'authorClasses' => 'Any class except the reserved .z-* namespace.',
            'authorProperties' => 'Any custom property except the reserved --z-* namespace.',
        ],
        'generatedPaths' => zeroy_runtime_theme_generated_paths(),
        'guidance' => 'Use manifest-declared custom CSS freely for the visual implementation: custom selectors, properties, Grid, Flex, gradients, pseudo-elements, animation and responsive queries are valid. zcss.design.json supplies compiler-generated defaults; public primitives and --z-* tokens are optional reusable building blocks, not an authoring limit. Generated paths and the reserved .z-* / --z-* namespaces remain compiler-owned.',
    ];
}

function zeroy_runtime_zcss_error(array $compilation): WP_Error
{
    $diagnostics = is_array($compilation['diagnostics'] ?? null) ? $compilation['diagnostics'] : [];
    $first = $diagnostics[0] ?? [];
    return zeroy_runtime_error(
        'zeroy_zcss_compile_failed',
        is_string($first['path'] ?? null) ? 'ZCSS design failed at ' . ($first['path'] === '' ? '/' : $first['path']) . ': ' . ($first['constraint'] ?? 'invalid design') : 'ZCSS design could not be compiled.',
        409,
        [
            'compiler' => ['id' => ZEROY_ZCSS_COMPILER_ID, 'version' => ZEROY_ZCSS_COMPILER_VERSION, 'sourceHash' => zeroy_zcss_compiler_source_hash()],
            'diagnostics' => $diagnostics,
        ],
    );
}

/**
 * The SiteCheckout compiler is the only filesystem adapter around the pure ZCSS
 * compiler. It always replaces both derived paths before ThemeArtifact bytes
 * are hashed; request runtime never calls this function.
 */
function zeroy_runtime_compile_zcss_directory(string $directory): array|WP_Error
{
    $theme_manifest = zeroy_runtime_theme_runtime_manifest($directory);
    if (is_wp_error($theme_manifest)) return $theme_manifest;
    $design_path = rtrim($directory, '/') . '/' . $theme_manifest['zcss']['design'];
    $design = zeroy_runtime_decode_json((string) file_get_contents($design_path));
    if (is_wp_error($design)) return zeroy_runtime_error('zeroy_zcss_design_invalid', 'zcss.design.json must contain valid JSON.', 409, ['fieldId' => '/zcss/design']);
    $compilation = zeroy_zcss_compile($design);
    if (($compilation['ok'] ?? false) !== true) return zeroy_runtime_zcss_error($compilation);
    foreach ([ZEROY_ZCSS_GENERATED_CSS_PATH => $compilation['css'], ZEROY_ZCSS_COMPILED_MANIFEST_PATH => $compilation['manifestJson']] as $path => $bytes) {
        $target = rtrim($directory, '/') . '/' . $path;
        if (!wp_mkdir_p(dirname($target)) || file_put_contents($target, $bytes, LOCK_EX) !== strlen($bytes)) {
            return zeroy_runtime_error('zeroy_zcss_output_write_failed', 'SiteCheckout compiler could not write a derived ZCSS file.', 500, ['path' => $path]);
        }
    }
    return [
        'contract' => ZEROY_ZCSS_COMPILED_CONTRACT,
        'designHash' => $compilation['manifest']['designHash'],
        'outputHash' => $compilation['manifest']['outputHash'],
        'compiler' => $compilation['manifest']['compiler'],
        'tokenCount' => count($compilation['manifest']['tokens']),
        'primitiveCount' => count($compilation['manifest']['primitives']),
        'warnings' => $compilation['manifest']['warnings'],
        'stylesheets' => [ZEROY_ZCSS_GENERATED_CSS_PATH, ...$theme_manifest['zcss']['styles']],
    ];
}
